vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - donjayamanne.githistory
    - github.vscode-pull-request-github
